//
//  LegacyStringsParser.swift
//  LocalizedTranslate
//
//  Created by Coordinator & Sub-Agent 1 on 10/4/26.
//

import Foundation

public struct LegacyStringsParser {
    /// Parses a legacy .strings file format: "key" = "value";
    public static func parse(content: String) -> [String: String] {
        var results: [String: String] = [:]
        let lines = content.components(separatedBy: .newlines)

        let pattern = #"^\s*"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;"#
        guard let regex = try? NSRegularExpression(pattern: pattern, options: []) else {
            return results
        }

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("//") || trimmed.hasPrefix("/*") || trimmed.isEmpty {
                continue
            }
            let range = NSRange(trimmed.startIndex..<trimmed.endIndex, in: trimmed)
            if let match = regex.firstMatch(in: trimmed, options: [], range: range),
               match.numberOfRanges == 3 {
                if let keyRange = Range(match.range(at: 1), in: trimmed),
                   let valRange = Range(match.range(at: 2), in: trimmed) {
                    let key = unescapeString(String(trimmed[keyRange]))
                    let val = unescapeString(String(trimmed[valRange]))
                    results[key] = val
                }
            }
        }
        return results
    }

    /// Converts dictionary to .strings file format
    public static func serialize(_ dict: [String: String]) -> String {
        var output = "/* Generated by LocalizedTranslate (L10n Studio) */\n\n"
        for key in dict.keys.sorted() {
            guard let val = dict[key] else { continue }
            let escapedKey = escapeString(key)
            let escapedVal = escapeString(val)
            output += "\"\(escapedKey)\" = \"\(escapedVal)\";\n"
        }
        return output
    }

    /// Imports a legacy .strings dictionary into a StringCatalog for target language
    public static func mergeIntoCatalog(
        catalog: StringCatalog,
        strings: [String: String],
        language: String
    ) {
        for (key, value) in strings {
            if let group = catalog.strings[key] {
                group.setTranslation(value, for: language)
            } else {
                let group = LocalizationGroup()
                group.setTranslation(value, for: language)
                catalog.strings[key] = group
            }
        }
    }

    private static func unescapeString(_ str: String) -> String {
        str.replacingOccurrences(of: "\\\"", with: "\"")
            .replacingOccurrences(of: "\\n", with: "\n")
            .replacingOccurrences(of: "\\t", with: "\t")
            .replacingOccurrences(of: "\\\\", with: "\\")
    }

    private static func escapeString(_ str: String) -> String {
        str.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\t", with: "\\t")
    }
}
